version: '3.9'
services:
  traefik:
    image: traefik:${TRAEFIK_VERSION}
    container_name: traefik
    restart: on-failure
    command:
      - --entrypoints.web.address=:80
      - --entrypoints.web.http.redirections.entryPoint.to=websecure
      - --entrypoints.web.http.redirections.entryPoint.scheme=https
      - --entrypoints.websecure.address=:443
      - --certificatesresolvers.ghost-certresolver.acme.email=${ACME_EMAIL}
      - --certificatesresolvers.ghost-certresolver.acme.storage=/letsencrypt/acme.json
      - --certificatesresolvers.ghost-certresolver.acme.httpchallenge.entrypoint=web
      - --providers.docker
      - --providers.docker.exposedbydefault=false
      - --providers.file.filename=/etc/traefik/traefik-dyn.toml
      - --log.level=INFO
      - --accesslog=true
      - --api.dashboard=true
      - --api.insecure=true
      - --entryPoints.ping.address=:8082
      - --ping.entryPoint=ping
      - --ping=true
    ports:
      - "80:80"
      - "443:443"
      - "127.0.0.1:8080:8080"
    volumes:
      - "/var/run/docker.sock:/var/run/docker.sock:ro"
      - letsencrypt-data:/letsencrypt
      - ./traefik-dyn.toml:/etc/traefik/traefik-dyn.toml
    healthcheck:
      interval: 3s
      timeout: 3s
      retries: 5
      test: traefik healthcheck --ping  --entryPoints.ping.address=:8082 --ping.entryPoint=ping

  ghost:
    image: ghost:${GHOST_VERSION}
    container_name: ghost
    restart: on-failure
    environment:
      - url=https://${HOST}
      - mail__transport=SMTP
      - mail__from=${MAIL_FROM}
      - mail__options__host=${MAIL_HOST}
      - mail__options__port=${MAIL_PORT}
      - mail__options__secure=true
      - mail__options__auth__user=${MAIL_USER}
      - mail__options__auth__pass=${MAIL_PASS}
    labels:
      - traefik.enable=true
      - traefik.http.routers.ghost.tls=true
      - traefik.http.routers.ghost.tls.certresolver=ghost-certresolver
      - traefik.http.routers.ghost.rule=Host(`${HOST}`)
      - traefik.http.routers.ghost.entrypoints=websecure
      - traefik.http.services.ghost.loadbalancer.server.port=2368
    volumes:
      - ghost-data:/var/lib/ghost/content
    healthcheck:
      interval: 10s
      timeout: 3s
      retries: 5
      test: timeout 3 bash -c '</dev/tcp/ghost/2368'

volumes:
  ghost-data:
    driver: local
  letsencrypt-data:
    driver: local
